name: 更新EPG节目单

on:
  workflow_dispatch:  # 手动触发
  schedule:
  # 北京时间凌晨2点 = UTC时间前一天18点
  #- cron: '15 16,18,20,22,0,2,4,6,8,10,12,14 * * *'
  #- cron: '15 18 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: 下载EPG节目单
      run: |
        wget -q https://epg.112114.xyz/pp.xml -O 1day112114_epg.xml

    - name: 开始推送
      run: |
        # 配置Git
        git config --global user.name "Auto Sync"
        git config --global user.email "auto@sync.com"
        USER="tyrian9905"
        REPO="iptv"
        
        # 获取北京时间
        export TZ='Asia/Shanghai'
        BEIJING_TIME=$(date '+%Y-%m-%d %H:%M:%S')
        
        # 克隆仓库
        git clone https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/${USER}/${REPO}.git
        
        # 进入仓库并更新文件
        cd ${REPO}
        
        # 确保目录存在
        mkdir -p iptv
        
        # 复制所有广告规则文件
        cp ../*.xml ./ 2>/dev/null || true
        
        # 添加dnsblock目录下所有文件
        #git add iptv/
        git add .
        
        # 检查是否有变更
        if ! git diff --cached --quiet; then
          git commit -m "自动同步文件 ${BEIJING_TIME}"
          git push origin master
          echo "✅ 文件已同步！"
        else
          echo "⚠️ 没有文件变更，跳过提交"
        fi
        
        echo "🎉 节目单EPG成功！"
