
name: 更新广告过滤文件

on:
  workflow_dispatch:  # 手动触发
  schedule:
    # 北京时间凌晨2点 = UTC时间前一天18点
    - cron: '40 16,0,8 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: 下载广告过滤文件
      run: |
        wget -q https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockfilterslite.txt -O 217heidai_adblockfilterslite.adb
        wget -q https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdnslite.txt -O 217heidai_adblockdnslite.adb
        wget -q https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdnsmasqlite.txt -O 217heidai_adblockdnsmasqlite.adb
        wget -q https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdomainlite.txt -O 217heidai_adblockdomainlite.adb
        wget -q https://cnb.cool/tyrian9905/work/-/git/raw/main/adblock/YXdnsmasq.txt -O yxdnsmasq.txt
        cat yxdnsmasq.txt >> 217heidai_adblockdnsmasqlite.adb

    - name: 开始推送
      run: |
        # 配置Git
        git config --global user.name "Auto Sync"
        git config --global user.email "auto@sync.com"
        USER="tyrian9905"
        REPO="work"
        
        # 获取北京时间
        export TZ='Asia/Shanghai'
        BEIJING_TIME=$(date '+%Y-%m-%d %H:%M:%S')
        
        # 克隆仓库
        git clone https://oauth2:${{ secrets.CNB_TOKEN }}@cnb.cool/${USER}/${REPO}.git
        
        cd ${REPO}
        
        # 确保目录存在
        mkdir -p adblock
       
        # 复制所有广告规则文件
        # cp ../*.txt ../*.adb ./adblock/ 2>/dev/null || true
        cp ../*.adb ./adblock/ 2>/dev/null || true
        git add adblock/
        
        # 检查是否有变更
        if ! git diff --cached --quiet; then
          git commit -m "自动同步DNS过滤文件 ${BEIJING_TIME}"
          git push origin main
          echo "✅ 文件已同步！"
        else
          echo "⚠️ 没有文件变更，跳过提交"
        fi
